name: meisterdirekt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  flutter_animate: ^4.5.0

  # Firebase Core
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.1
  firebase_storage: ^11.7.7
  uuid: ^3.0.7

  # File picking for images, videos, and PDFs
  file_picker: ^8.0.7
  video_player: ^2.8.1
  chewie: ^1.7.5
  
  # For GeoLocation
  geolocator: ^12.0.0
  geocoding: ^3.0.0

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_profile.png
    - assets/data/initial_services.json
    - assets/icons/carpentry.png
    - assets/icons/electrical.png # تأكد من أن هذا الاسم صحيح (وليس electrical.png)
    - assets/icons/plumbing.png
    - assets/icons/painting.png
    - assets/icons/cleaning.png
    - assets/icons/ac.png
    - assets/images/meisterdirekt_logo.png
    - assets/images/customer_login_icon.png
    - assets/images/artisan_login_icon.png
    - assets/images/logo.png # تأكد من وجود هذا إذا كان يستخدم في SplashScreen
