// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsDju6PG9DCIo7NeXoc4wD3RCG-z5eCNw',
    appId: '1:936025691984:web:67055daf58905815067e55',
    messagingSenderId: '936025691984',
    projectId: 'meister_direkt-902e4',
    authDomain: 'meister_direkt-902e4.firebaseapp.com',
    storageBucket: 'meister_direkt-902e4.firebasestorage.app',
    measurementId: 'G-XNDNEYHQQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC-9K-Xl_Qt3b7hoy3JfPFgwNQuK18XtE',
    appId: '1:936025691984:android:8925f99a3b771ad6067e55',
    messagingSenderId: '936025691984',
    projectId: 'meister_direkt-902e4',
    storageBucket: 'meister_direkt-902e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTGIj5T0EDrkg409pmr_8285Vt6dJEtM',
    appId: '1:936025691984:ios:7192f9a76665900a067e55',
    messagingSenderId: '936025691984',
    projectId: 'meister_direkt-902e4',
    storageBucket: 'meister_direkt-902e4.firebasestorage.app',
    iosBundleId: 'com.example.meister_direkt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQTGIj5T0EDrkg409pmr_8285Vt6dJEtM',
    appId: '1:936025691984:ios:7192f9a76665900a067e55',
    messagingSenderId: '936025691984',
    projectId: 'meister_direkt-902e4',
    storageBucket: 'meister_direkt-902e4.firebasestorage.app',
    iosBundleId: 'com.example.meister_direkt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsDju6PG9DCIo7NeXoc4wD3RCG-z5eCNw',
    appId: '1:936025691984:web:a863b44671790669067e55',
    messagingSenderId: '936025691984',
    projectId: 'meister_direkt-902e4',
    authDomain: 'meister_direkt-902e4.firebaseapp.com',
    storageBucket: 'meister_direkt-902e4.firebasestorage.app',
    measurementId: 'G-S658CWKXFN',
  );
}
